# Generated by Django 3.1.3 on 2021-01-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mlclient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlclient',
            old_name='address',
            new_name='Client_address',
        ),
        migrations.RenameField(
            model_name='mlclient',
            old_name='email',
            new_name='Client_email',
        ),
        migrations.RenameField(
            model_name='mlclient',
            old_name='name',
            new_name='Client_name',
        ),
        migrations.RenameField(
            model_name='mlclient',
            old_name='phone',
            new_name='Client_phone',
        ),
    ]
