# Generated by Django 3.1.3 on 2020-12-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ID', models.CharField(choices=[('project1', 'project1'), ('project2', 'project2'), ('project3', 'project3')], default=None, max_length=100)),
                ('element_ID', models.CharField(blank=True, max_length=1000, null=True)),
                ('filename', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Projectsdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ID', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_Work_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_points', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MlUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('labels_selected', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('labels_done', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('labels_correct', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('labels_incorrect', models.CharField(blank=True, default=0, max_length=1000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
