# Generated by Django 3.1.3 on 2021-01-07 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='Allocated_to_User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elements',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Allocated', 'Allocated'), ('Labeled', 'Labeled'), ('Unclear', 'Unclear')], default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projectsdetail',
            name='Total_elements',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='elements',
            name='element_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='elements',
            name='filename',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='project_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.projectsdetail'),
        ),
    ]
