# Generated by Django 3.1.3 on 2020-11-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
