# Generated by Django 3.1.3 on 2021-01-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210107_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='Allocated_to_User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.mluser'),
        ),
    ]
