# Generated by Django 3.1.3 on 2020-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mluser',
            name='labels_correct',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mluser',
            name='labels_done',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mluser',
            name='labels_incorrect',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mluser',
            name='labels_selected',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
