# Generated by Django 3.1.3 on 2020-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201215_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='mluser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mluser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
