# Generated by Django 3.1.3 on 2020-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201215_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectsdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.CharField(blank=True, max_length=100, null=True)),
                ('project_Work_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_points', models.CharField(blank=True, max_length=100, null=True)),
                ('project_status', models.BooleanField(default=False)),
            ],
        ),
    ]
