# Generated by Django 3.1.3 on 2020-12-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201217_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('project_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projectsdetail')),
            ],
        ),
    ]
