# Generated by Django 3.1.3 on 2020-12-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201223_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='element_ID',
        ),
    ]
