# Generated by Django 3.1.3 on 2020-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_elements_element_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='element_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
