# Generated by Django 3.1.3 on 2020-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_elements_element_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='project_ID',
        ),
        migrations.AddField(
            model_name='elements',
            name='project_ID',
            field=models.ManyToManyField(null=True, to='base.Projectsdetail'),
        ),
    ]
