# Generated by Django 3.1.3 on 2020-12-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201223_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='element_ID',
        ),
    ]
