# Generated by Django 3.1.3 on 2020-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_elements_element_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='project_ID',
            field=models.CharField(choices=[('project1', 'project1'), ('project2', 'project2'), ('project3', 'project3')], default=None, max_length=100),
        ),
    ]
